export const dummyAllPortfolioList = [
  {
    id: 3,
    name: "닥터에버스의원 명동점",
    alias: "명동 닥터에버스 6층",
    title: "번화가 속, 고요한 환대로 맞이하는 피부과",
    location: "서울 중구 퇴계로",
    role: "설계, 시공, 장애인 편의시설 설치",
    category: "피부과",
    area: "600㎡",
    imageSrc: "/recent-1.jpg",
    thumbnail: "/evers/thumbnail.jpg",
    photos: [
      "/evers/evers-1.jpg",
      "/evers/evers-2.jpg",
      "/evers/evers-3.jpg",
      "/evers/evers-4.jpg",
      "/evers/evers-5.jpg",
      "/evers/evers-6.jpg",
      "/evers/evers-7.jpg",
      "/evers/evers-8.jpg",
      "/evers/evers-9.jpg",
      "/evers/evers-10.jpg",
    ],
    descriptions: [
      "최근 가장 활발하게 부활 중인 명동 상권 초입에 위치한 이 건물은 1960년대 준공되었음에도 우수한 컨디션으로 유지되고 있었습니다. 이는 건물 관리가 철저히 이루어졌다는 의미인 동시에, 디자인 승인, 공사 관리, 장애인 편의시설 설치 등을 위해 많은 협의가 필요했다는 것을 뜻하기도 합니다. 약 180평 규모의 피부과가 원활히 오픈할 수 있도록 세심하게 조율한 프로젝트였습니다.",
      "2024년 여름, 착공 반 년 전부터 입점 후보지를 답사하며 변화하는 명동 상권에 대한 이해를 높였습니다. 무엇보다 번잡한 도심 속에서도 고객을 차분하게 맞이할 수 있는 로비의 중요성을 인식했고, 대기 공간은 편안하게, 관리와 시술이 이루어지는 공간은 기능성과 적절한 조도 확보에 초점을 맞춰 설계했습니다.",
      "낮은 층고와 긴 복도가 답답해 보이지 않도록 벽과 천장에 디자인 요소를 가미해 공간감을 조정했습니다. 또한, 고객이 길을 쉽게 찾을 수 있도록 사이니지를 정교하게 설계했으며, 직원과 부원장님의 위치를 직관적으로 파악할 수 있는 시각적 요소도 원장님과 협의하여 반영했습니다.",
    ],
  },
  {
    id: 2,
    name: "태즈풋볼 논현점",
    alias: "태즈 풋볼 논현점",
    title: "커뮤니티 공간이 있는 실내 축구 교실",
    location: "서울 강남구 논현동",
    role: "설계 및 시공",
    category: "실내 축구장",
    area: "603.9㎡",
    imageSrc: "/recent-2.jpg",
    thumbnail: "/evers/thumbnail.jpg",
    photos: ["/evers/evers-1.jpg", "/evers/evers-2.jpg"],
  },
  {
    id: 1,
    name: "자승담 한의원",
    alias: "다산 자승담 한의원",
    title: "신도시로 이전하며 한의원이 경쟁력을 강조하고 싶습니다.",
    location: "경기 남양주시 다산동",
    role: "브랜딩, 설계 및 시공",
    category: "한의원",
    area: "106.4㎡",
    imageSrc: "/recent-3.jpg",
    thumbnail: "",
    photos: ["/evers/evers-1.jpg", "/evers/evers-2.jpg"],
  },
];

export const getPortfoliosById = (id) => {
  return dummyAllPortfolioList.filter((portfolio) => portfolio.id === id)?.[0];
};
